### ISSUE TITLE
Unusual Output When Using ntHash In Python

### ISSUE THREAD

**Issue by parham-k** [bcgsc/btllib#14]
Considering these two code snippets, the outputs of `ntHash_test.cpp` and `ntHash_test.py` are different.

# Expected Behaviour (C++)

`btllib/examples/ntHash_test.cpp`:

```c++
#include <iostream>
#include "../include/btllib/nthash.hpp"

int main()
{
    int k = 10;
    std::string seq = "AGTCATGATGCTAGCTACCAACAGTACGT";
    uint64_t hVal = btllib::ntf64(seq.substr(0, k).c_str(), k);
    std::cout << "kmer0\t0x" << std::hex << hVal << std::dec << std::endl;
    for (size_t i = 0; i < seq.length() - k; i++)
    {
        hVal = btllib::ntf64(hVal, k, seq[i], seq[i + k]);
        std::cout << "kmer" << i + 1 << "\t0x" << std::hex << hVal << std::dec << std::endl;
    }
    return 0;
}
```

Output:

```
kmer0   0x6e9073fad4d55d21
kmer1   0xc35def95d31b4225
kmer2   0x6715d7dfb1585119
kmer3   0xa78785457e67fcd0
kmer4   0x203b25d6fe35e840
kmer5   0x5e0b43cd86da28e7
kmer6   0xc0641f27cf474f0e
kmer7   0x74b884fd57c40b6d
kmer8   0xf70c0198d539eebc
kmer9   0x8aac13fd41c2aca3
kmer10  0xe1289d484acfcc37
kmer11  0xb1dcd0ad80f4aedf
kmer12  0x70db195ea582c64
kmer13  0x1d7e517f59678f96
kmer14  0xd235dd2d6c14ad0d
kmer15  0xc238e22313662c88
kmer16  0xedddeebe3a1b07f2
kmer17  0xc5c6d51e0e87f783
kmer18  0xe4b985621ff5fee7
kmer19  0xaf2052bff4a48b5d
```

# Current Behavior (Python)

`ntHash_test.py`:

```python
import btllib
import numpy as np

k = 10
seq = "AGTCATGATGCTAGCTACCAACAGTACGT"

h = btllib.ntf64(seq[:k], k)
print(f"kmer0\t{hex(np.uint64(h))}")
for i in range(len(seq) - k):
    h = btllib.ntf64(h, k, ord(seq[i]), ord(seq[i + k]))
    print(f"kmer{i + 1}\t{hex(np.uint64(h))}")
```

Output:

```
kmer0	0x5557f2204130
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer1	0x5557f22059e0
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer2	0x5557f2241f90
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer3	0x5557f2024ff0
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer4	0x5557f2340020
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer5	0x5557f239bf30
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer6	0x5557f19c0d30
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer7	0x5557f209a9d0
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer8	0x5557f21fd550
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer9	0x5557f238a680
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer10	0x5557f232edc0
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer11	0x5557f21f9420
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer12	0x5557f21eb400
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer13	0x5557f22077e0
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer14	0x5557f2288a00
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer15	0x5557f2289b60
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer16	0x5557f1fb9990
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer17	0x5557f217ecf0
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer18	0x5557f20b6be0
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
kmer19	0x5557f2006820
swig/python detected a memory leak of type 'uint64_t *', no destructor found.
```

# Environment

- OS: Manjaro (21.1.3) Linux (Kernel 5.14.2)
- Compiler: g++ (GCC) 11.1.0
- Python: 3.9
- I installed btllib's Python wrapper as explained in [the README](https://github.com/bcgsc/btllib/blob/master/README.md)

# Description

I used [ntHash's original implementation](https://github.com/bcgsc/ntHash) with `ntHash_test.cpp` and the output was similar to btllib in C++. Also, I wrote a simple native implementation of ntHash in Python and got the expected behaviour.

Note that casting the output of `btllib.ntf64(...)` in Python to either `int` or `np.uint64` raises an error on the next `ntf64` call:

```python
h = np.uint64(btllib.ntf64(seq[:k], k))  # or int(...)
...
for i in range(len(seq) - k):
    h = btllib.ntf64(h, k, ord(seq[i]), ord(seq[i + k]))
    ...


Traceback (most recent call last):
  File "btllib_output_test.py", line 17, in <module>
    h = btllib.ntf64(h, k, ord(seq[i]), ord(seq[i + k]))
TypeError: in method 'ntf64', argument 1 of type 'uint64_t const'
Additional information:
Wrong number or type of arguments for overloaded function 'ntf64'.
  Possible C/C++ prototypes are:
    btllib::ntf64(char const *,unsigned int const)
    btllib::ntf64(uint64_t const,unsigned int const,unsigned char const,unsigned char const)
    btllib::ntf64(char const *,unsigned int const,unsigned int const)
```

Not casting `seq[i]` or `seq[i + k]` to `int` using `ord` also raises a `TypeError` in `argument 3 of type 'unsigned char'`.

Am I calling `btllib.ntf64` incorrectly?

**Comment by vlad0x00** [comment]
It looks like the output of `ntf64` is an address of the array and not the actual ntHash output. The intended usage of ntHash in btllib is with the `NtHash` class:
`import btllib
nthash = btllib.NtHash("ACTGACTG", 3, 4)
while nthash.roll(): print(nthash.hashes())`
This would roll over the given string with a kmer size of 4 and output 3 hashes on each iteration. I compared it to the C++ version just now and it looks identical. You could technically call all the lower level functions like `ntf64` but it shouldn't be necessary and since they weren't intended to be used by wrappers they currently return address of the SWIG object instead of hash value.

> I used ntHash's original implementation with ntHash_test.cpp and the output was similar to btllib in C++.
What do you mean by similar? Were there any differences?

**Comment by parham-k** [comment]
> The intended usage of ntHash in btllib is with the `NtHash` class:

Oh ok. I didn't notice `class NtHash` because I was working on [nthash.hpp in ntHash's repo](https://github.com/bcgsc/ntHash/blob/master/nthash.hpp). My bad, thank you.

> It looks like the output of `ntf64` is an address of the array and not the actual ntHash output.

The output does look like an address but I'm just curious to know why. `uint64_t btllib::ntf64(const char*, const unsigned)` doesn't return an address in C++, [SWIG's docs](http://www.swig.org/Doc1.3/Python.html#Python_nn49) say that Python strings are passed as `char *`s so it shouldn't be a problem there, and I checked the output is not the address of the SWIG object created.

> What do you mean by similar? Were there any differences?

By similar I meant identical.

**Comment by vlad0x00** [comment]
The issue, I think, is that SWIG needs to be told about the existence of uint64_t and how to handle it, otherwise it just treats it as a SWIG object. I've pushed a couple of updates and it seems to return the actual hash value now. :D

**Comment by parham-k** [comment]
Cool! Case closed then :D
