### ISSUE TITLE
Issue with wrap script on mac

### ISSUE THREAD

**Issue by parham-k** [bcgsc/btllib#42]
When running `scripts/wrap` on mac, this error appears:
```
sed: 1: "btllib_wrap.cxx": undefined label 'tllib_wrap.cxx'
```
The problem is that the `-i` parameter in `sed` requires a value in BSD/Mac systems. Changing the last line to 
```bash
sed -i '' 's~unsigned long long~uint64_t~g' btllib_wrap.cxx
```
fixes this issue, but I'm not sure if:
- this will break the wrap script for Linux
- other `sed` commands in the script also need to be fixed

**Comment by vlad0x00** [comment]
We can add a check in the script whether it's Linux or Bash and call sed appropriately.

**Comment by vlad0x00** [comment]
Fixed in https://github.com/bcgsc/btllib/commit/7fe19e7579c6b05932d34cc422977b4c028efff1
