### ISSUE TITLE
Python version issue on install

### ISSUE THREAD

**Issue by berkeucar** [bcgsc/btllib#65]
Hello,

When I was trying to install btllib on my local, it could not install due to the Python version (I had 3.7.10 I believe). After checking the requirements from Bioconda, I figured out that it needs Python>3.9 and that worked well. I believe there is a ambiguity for the version of Python in the documentation.

Regards,
Berke Uçar

**Comment by parham-k** [comment]
Hi Berke and thank you for mentioning this. Python 3.9+ is indeed the safest minimum version for btllib. I'll update the readme to reflect it.
