### ISSUE TITLE
ERROR: C++ shared or static library 'btllib' not found

### ISSUE THREAD

**Issue by Duda5** [bcgsc/btllib#68]
I have successfully compiled `btllib` from source (Ubuntu 20.04), but when I am trying to compile packages that rely on it (such as [goldrush](https://github.com/bcgsc/goldrush)) I get the following error:

`subprojects/goldrush-edit/meson.build:37:0: ERROR: C++ shared or static library 'btllib' not found`

I added to `btllib` installation directory path to `~/.bashrc` file 

`export LD_LIBRARY_PATH="/home/duda5/soft/btllib-1.4.10/install/lib/:$LD_LIBRARY_PATH"`

Then I ran `source ~/.bashrc`, but I am still getting the same error.

**Comment by jowong4** [comment]
Hi,

Can you try the following
```export LDFLAGS="-L/home/duda5/soft/btllib-1.4.10/install/lib  $LDFLAGS" ```
```export CPPFLAGS="-isystem /home/duda5/soft/btllib-1.4.10/install/include $CPPFLAGS"```

and see if it resolves your problem

**Comment by Duda5** [comment]
Hi, @jowong4 
It works now. Thanks!
