### ISSUE TITLE
Adapt code to C++17 standards

### ISSUE THREAD

**Issue by parham-k** [bcgsc/btllib#90]
btllib is implemented with C++11 standards. Compiling with C++17 (e.g., for `argparse` used in `randseq`) causes `clang-tidy` to raise errors. Currently, we compile `randseq` with C++17 and the rest of btllib with C++11, but it'd be better if we refactor the library with C++17 standards in mind.

**Comment by lcoombe** [comment]
Hey @parham-k - looks like were are compiling with c++17 in the top-level `meson.build` now? Is this closable?

**Comment by parham-k** [comment]
Yes, I'll close this now.
